const ipcConstants = {
  CHECK_EXISTING_USER: 'CHECK_EXISTING_USER',
  GENERATE_CREDENTIALS: 'GENERATE_CREDENTIALS',
  SRP_GET_A: 'SRP_GET_A',
  STORE_LOCAL_CONFIG: 'STORE_LOCAL_CONFIG',
  UNLOCK_USER_CREDENTIALS: 'UNLOCK_USER_CREDENTIALS',
};

export default ipcConstants;
