const ipcConstants = {
  CHECK_EXISTING_USER: 'CHECK_EXISTING_USER',
  DEBUG_SRP: 'DEBUG_SRP',
  GENERATE_CREDENTIALS: 'GENERATE_CREDENTIALS',
  SRP_GET_A: 'SRP_GET_A',
  SRP_GET_M: 'SRP_GET_M',
  SRP_VALIDATE_HAMK: 'SRP_VALIDATE_HAMK',
  STORE_LOCAL_CONFIG: 'STORE_LOCAL_CONFIG',
  UNLOCK_USER_CREDENTIALS: 'UNLOCK_USER_CREDENTIALS',
  GET_ENCRYPTED_PHOTO: 'GET_ENCRYPTED_PHOTO',
};

export default ipcConstants;
